name: CI - Java

on:
  push:
    paths:
      - 'java/v1/**'
      - 'spec/**'
      - '.github/workflows/ci-java.yml'
  pull_request:
    paths:
      - 'java/v1/**'
      - 'spec/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java/v1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - run: ./gradlew test
