name: CI - Python

on:
  push:
    paths:
      - 'python/v1/**'
      - '.github/workflows/ci-python.yml'
  pull_request:
    paths:
      - 'python/v1/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/v1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - run: pip install -e ".[dev]"
      - run: pytest
